### ISSUE TITLE
Google Cloud Console problem

### ISSUE THREAD

**Issue by csspcc** [websightgmbh/l5-google-cloud-storage#1]
Thanks for this Service Provider. Everything seems to work, but I have this one weird bug though.

When I upload a file via Google Cloud Platform Console or gsutil everything is fine, but when I upload a file via this GCSServiceProvider (I use it on Laravel 5.2) I see this in Console. Basically, I can't share my file or edit it via Console. What can I do?

![screenshot](https://cloud.githubusercontent.com/assets/13589770/12533260/e620082e-c232-11e5-8cb1-68aa23d9f475.png)

**Comment by cedricziel** [comment]
Thank you for reporting. I will definitely look into it. Most probably this boils down to the available options on the save operation.

**Comment by cedricziel** [comment]
I can reproduce the state your screenshot shows. Though the file, when uploaded with the public attribute is publicliy accessible.

**Comment by cedricziel** [comment]
Short update: It's a little more complicated to fiddle with the ACL. Please track Superbalist/flysystem-google-storage#3 for updates in the meantime.

**Comment by cedricziel** [comment]
I submitted a pull request to the upstream project that fixes the permission problem.

**Comment by csspcc** [comment]
Thanks so much for investigating this.

**Comment by cedricziel** [comment]
Alright - my patch to the upstream project was accepted. Either use `superbalist/flysystem-google-storage dev-master` or wait a moment until they tag a new release.

I'll close the issue now, but please feel free to reopen if you experience any problems.
For any existing files you need to toggle the visibility or impersionate as the service account and reset the acl.

Thanks for reporting the issue! :)
