### ISSUE TITLE
Undefined index: service_account

### ISSUE THREAD

**Issue by twisctid** [websightgmbh/l5-google-cloud-storage#11]
Hey,

So I don't know what's happening but following your example to the T throws the above exception.
I have driver, credentials, project_id and bucket configured and my service account created in google console.

**Comment by cedricziel** [comment]
You most probably used the documentation for dev-master for an installed v1, can you please check which version you installed?

**Comment by twisctid** [comment]
version 1.1

**Comment by cedricziel** [comment]
The README for v1.1 is here: https://github.com/websightgmbh/l5-google-cloud-storage/blob/v1.1.0/README.md#google-cloud-storage-serviceprovider-for-laravel-5-apps

**Comment by twisctid** [comment]
Correct! Thanks!
