### ISSUE TITLE
Don't swallow exceptions and give a generic message

### ISSUE THREAD

**Issue by atrauzzi** [websightgmbh/l5-google-cloud-storage#2]
https://github.com/websightgmbh/l5-google-cloud-storage/blob/master/src/Websight/GcsProvider/CloudStorageServiceProvider.php#L48

Throwing a generic message inside an `ErrorException` is not really helpful here and doesn't assist with troubleshooting configuration.

I'd suggest just removing the try catch block entirely.

**Comment by cedricziel** [comment]
Thanks for pointing the smell out. Very appreciated.

**Comment by atrauzzi** [comment]
:+1:
