### ISSUE TITLE
Laravel 5.4 supported? 

### ISSUE THREAD

**Issue by wammy21** [websightgmbh/l5-google-cloud-storage#21]
Installing on the latest laravel 5.4 release, upgrading to dev-master (from 1.0) I am getting this error:

In CloudStorageServiceProvider.php line 54:

  Call to undefined method Illuminate\Foundation\Application::has()

I'm not particularly sure where it is coming from, I am not finding anything related to Illuminate\Foundation\Application::has()

**Comment by cedricziel** [comment]
I am pretty sure this stems from #18 . - This could be fixed through checking for the existence of the method - can you provide a pull-request?

**Comment by wammy21** [comment]
@cedricziel Sorry for the delay. I will submit a pr in the next few days.

**Comment by wammy21** [comment]
I've submitted a pull request #22 

Let me know if this is appropriate or if you require any changes.
