### ISSUE TITLE
Have an error..

### ISSUE THREAD

**Issue by ghost** [websightgmbh/l5-google-cloud-storage#6]
{"error":{"message":"Error refreshing the OAuth2 token, message: '{\n  \"error\" : \"deleted_client\",\n  \"error_description\" : \"The OAuth client was deleted.\"\n}'","code":401,"status_code":500}}

**Comment by ghost** [comment]
What can i do with it?

I changed some info in service accounts - but not delete it. Then have an error.

**Comment by cedricziel** [comment]
The fix is easy: Use a service account that still exists - sorry, but I don't think we can be of any help here.

**Comment by ghost** [comment]
so i merged service accounts to one. Sorry for reached time. Thats really easy))

**Comment by cedricziel** [comment]
You're welcome :)

**Comment by ghost** [comment]
So have an another error 
Invalid JWT: Token must be a short-lived token and in a reasonable timeframe
