### ISSUE TITLE
Get path of a file

### ISSUE THREAD

**Issue by devthiagolino** [websightgmbh/l5-google-cloud-storage#7]
How to retrieve the path of a file? I can not in any way.

**Comment by cedricziel** [comment]
Could you go a little more into detail?

The normal flysystem API also applies to the underlying [`superbalist/flysystem-google-storage`](https://packagist.org/packages/superbalist/flysystem-google-storage) this package utilizes.

This package is just a very thin wrapper. Maybe you want to get familiar with flysystem first?

**Comment by devthiagolino** [comment]
I need to retrieve the file path to generate a zip file of all user-informed files.

**Comment by cedricziel** [comment]
Did you look into the flysystem api? You can absolutely read what you need from the `File` objects. You will, however, need to retrieve them and package them up locally.

**Comment by thebrubaker** [comment]
Maybe a similar issue - how do I get the URL of the file once it's been stored? With local disk I might run Storage::url($filename) but it's not supported with this package.

Any tips or advice on grabbing that absolute url to the file once it has been stored?

Thanks!

**Comment by thebrubaker** [comment]
Nevermind I take it back, it follows a pretty basic convention of gcs domain + bucket + filename.

**Comment by giaphiep** [comment]
You can get url like that.
http://BUCKET_NAME.storage.googleapis.com/OBJECT_NAME
or
http://storage.googleapis.com/BUCKET_NAME/OBJECT_NAME

**Comment by cedricziel** [comment]
I believe anything you need can be accomplished by operating directly on the disk, rather than the `Storage` facade. 

I'm closing this for now, but feel free to discuss any further
